### ISSUE TITLE
Dockerize app

### ISSUE THREAD

**Issue by nuest** [sitcomlab/Ethics-app#20]
For other users and also for testing and deployment, it would be useful to prove a Dockerfile and a docker-compose configuration.

Let me know if you would welcome such a contribution.

**Comment by nicho90** [comment]
Yes, totally! 👍

**Comment by nuest** [comment]
I've created a first prototype, which is based on 

- this blog post: https://github.com/BretFisher/node-docker-good-defaults
- a Dockerimage we use in our project: https://github.com/o2r-project/o2r-muncher/blob/master/Dockerfile
- alpine base images for small image sizes

See branch **https://github.com/nuest/Ethics-app/tree/docker**

## Status (will update here)

Dockerfile builds and can be run with `make run_dev`.

```
~/git/Ethics-app/docker$ make run_dev
docker run -it -e NODE_ENV=development ethics-app
Tue May 30 2017 15:58:23 GMT+0000 (UTC) HTTP-Server is listening at port undefined
{ Error: connect ECONNREFUSED 127.0.0.1:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432 }
Tue May 30 2017 15:58:23 GMT+0000 (UTC) Could not connect to Database! Invalid Credentials or Postgres is not running
```

## Issues & Open Tasks

- fix configuration (see `server.js` changes) to actually use defaults for missing env variables
- postgres initialisation: you're using `setup.js`, but the Postgres image requires `.sql` or `.sh` scripts, see section _"How to extend this image"_ at https://hub.docker.com/_/postgres/
- add `dump-init`, see https://github.com/Yelp/dumb-init

## Build hooks

I've also added build hooks for Docker Hub - if you don't want to publish the image there these could be removed again. For documentation see

- https://docs.docker.com/docker-cloud/builds/advanced/#override-build-test-or-push-commands
- https://github.com/rossf7/label-schema-automated-build
- https://gist.github.com/DarrenN/8c6a5b969481725a4413

## Next steps

Further things that could be done:

- a container running the cleaning up cron job (and potentially other cron jobs)
